global_costmap:
  global_frame: map
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 20
  height: 20
  origin_x: -10.0  #-7.5
  origin_y: -10.0  #-7.5
  static_map: true
  rolling_window: true
  resolution: 0.05
  plugins:
    - {name: static_layer,           type: "mw_costmap::StaticLayer"}
    - {name: obstacle_layer,         type: "mw_costmap::ObstacleLayer"}
    - {name: inflation_layer,        type: "mw_costmap::InflationLayer"}
  inflation_layer:
    cost_scaling_factor: 3.0
    inflation_radius: 0.4