trajectory_planner:

# Robot Configuration Parameters
  max_vel_x: 1.5
  min_vel_x: 0.1

  max_vel_theta:  1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.314

  acc_lim_x: 5.0
  acc_lim_y: 0.0
  acc_lim_theta: 5.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.15

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 10
  vtheta_samples: 30
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  heading_lookahead: 0.325

# Robot Footprint
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    radius: 0.2 # for type "circular"
    vertices: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]] # for type "polygon"
    padding: 0.01

# Cost Weights 
  pdist_scale: .74 #0.6
  gdist_scale: 1.0 #0.8
  occdist_scale: 0.1 #0.01

  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1 
  escape_vel: -0.1

  dwa: false
  heading_scoring: false
  heading_scoring_timestep: 0.8 #0.1

  simple_attractor: false

  #y_vels: [-0.3, -0.1, 0.1, 0.3]
